### ISSUE TITLE
AppStore country information is required.

### ISSUE THREAD

**Issue by Nerdfrenz** [robingenz/capacitor-app-update#23] opened 2021-09-23 14:24 UTC
I tried to check why am I can't get the version from our app through the SOURCE for iOS you wrote. 
As a result, when searching for information by bundleID in itunes, we found that the search criteria did not include countries. Of course, if it's the USA, it won't be a big problem, but for certain apps, you can target specific countries and distribute them. That's the case with the apps we've built. 
To solve this problem, we would like you to put a condition to add the country name to the part to check the update information.

An example is below.

ex)
https://itunes.apple.com/lookup?bundleId=org.nerdfriends.ddoit.app => No results found.

https://itunes.apple.com/lookup?bundleId=org.nerdfriends.ddoit.app&country=kr => The search results are checked.

**Comment by robingenz** [comment] 2021-09-25 08:25
Thank you for your request. This is a known issue that I will address in the near future. Since this issue is a duplicate of #12 , I will close this one.

**Closed by robingenz** 2021-09-25 08:25 UTC
