### ISSUE TITLE
bug: Unregistered Play Core listener should not be null

### ISSUE THREAD

**Issue by sverdlov** [robingenz/capacitor-app-update#35] opened 2022-01-26 08:12 UTC
**Plugin version:**
1.3.0

**Platform(s):**
Android

**Current behavior:**
Catch a crash in Firebase Crashlytics
AppUpdatePlugin.java line 169
dev.robingenz.capacitor.appupdate.AppUpdatePlugin.handleOnActivityResult

Some of logs
```
Caused by java.lang.NullPointerException: Unregistered Play Core listener should not be null.
       at com.google.android.play.core.internal.aw.d(:7)
       at com.google.android.play.core.listener.b.g(:13)
       at com.google.android.play.core.appupdate.e.unregisterListener(:3)
       at dev.robingenz.capacitor.appupdate.AppUpdatePlugin.handleOnActivityResult(AppUpdatePlugin.java:169)
       at com.getcapacitor.Bridge.onActivityResult(Bridge.java:1017)
       at com.getcapacitor.BridgeActivity.onActivityResult(BridgeActivity.java:215)
       at android.app.Activity.dispatchActivityResult(Activity.java:8320)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5198)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4529)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4582)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:181)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:102)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2235)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:240)
       at android.app.ActivityThread.main(ActivityThread.java:7829)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1027)
```

**Other information:**
Device Brand: OPPO
Model: CPH2185
Operating System Version: Android 10

**Capacitor doctor:**

```
@capacitor/cli: 3.3.3
@capacitor/android: 3.3.3
@capacitor/core: 3.3.3
@capacitor/ios: 3.3.3
```

**Comment by robingenz** [comment] 2022-01-26 08:41
Hi @sverdlov, 
thank you for your request!
This seems like a duplicate of #34. For this reason, I am closing this issue.
I will release a fix today.

**Closed by robingenz** 2022-01-26 08:41 UTC
Labels: bug/fix, duplicate, platform: android
